agro_marketplace/agro_marketplace/accounts/urls.py
from django.urls import path, include

from agro_marketplace.accounts import views
from agro_marketplace.accounts.views import EditProfileView

urlpatterns = [
    path('register/', views.AppUserRegisterView.as_view(), name='register'),
    path('registration/', views.ProfileRegistrationView.as_view(), name='profile-registration'),
    path('login/', views.AppUserLoginView.as_view(), name='login'),
    path('logout/', views.custom_logout, name='logout'),
    path('<int:pk>/', include([
        path('edit/', EditProfileView.as_view(), name='profile-edit'),
        path('details/', views.profile_details, name='profile-details'),
        path('delete-profile/', views.ProfileDeleteView.as_view(), name='profile-delete'),
        path('active/', views.activ_listings, name='active-listings'),
        path('inactive/', views.inactive_listings, name='inactive-listings'),
    ])),
    path('<slug:slug>/', include([
        path('activate/', views.activate_item, name='activate-item'),
        path('delete-item/', views.delete_item, name='delete-item'),
    ]))
]

agro_marketplace/agro_marketplace/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('agro_marketplace.common.urls')),
    path('accoutnts/', include('agro_marketplace.accounts.urls')),
    path('messages/', include('agro_marketplace.agro_messages.urls')),
    path('buyers/', include('agro_marketplace.buyers.urls')),
    path('sellers/', include('agro_marketplace.sellers.urls')),
]

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

agro_marketplace/agro_marketplace/accounts/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import AbstractUser, PermissionsMixin
from django.db import models

from agro_marketplace.accounts.choices import CountryCode
from agro_marketplace.accounts.managers import AppUserManager


class AppUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(
        max_length=100,
        unique=True
    )
    email = models.EmailField(
        unique=True
    )

    is_active = models.BooleanField(
        default=True
    )
    is_staff = models.BooleanField(
        default=False
    )

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = AppUserManager()

    def __str__(self):
        return self.username


UserModel = get_user_model()


class Profile(models.Model):

    user = models.OneToOneField(
        to=UserModel,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    profile_photo = models.ImageField(
        upload_to='profile_photo/',
        blank=True,
        null=True
    )

    full_name = models.CharField(
        max_length=100,
        null=True,
        blank=True)

    username_in_marketplace = models.CharField(
        max_length=100,
        unique=True,
        null=True,
        blank=True)

    email = models.EmailField(
        default='default@example.com'
    )

    description = models.CharField(
        max_length=500,
        blank=True,
        null=True
    )

    country_code = models.CharField(
        max_length=5,
        choices=CountryCode.choices,
        blank=True,
        null=True
    )

    phone = models.CharField(
        max_length=15,
        blank=True,
        null=True
    )

    town = models.CharField(
        max_length=100,
        blank=True,
        null=True
    )

    created_at = models.DateTimeField(
        auto_now_add=True
    )

    def __str__(self):
        return self.full_name

agro_marketplace/agro_marketplace/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm, UserCreationForm, AuthenticationForm

from agro_marketplace.accounts.mixins import EmailFormMixin
from agro_marketplace.accounts.models import Profile
from django.core.exceptions import ValidationError


UserModel = get_user_model()


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        labels = {
            'username': 'Username',
            'password': 'Password',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = field.widget.attrs.get('class', '') + ' form-control'
            field.widget.attrs['placeholder'] = f"Enter {self.Meta.labels.get(field_name, field_name).lower()}"


class AppUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = UserModel


class AppUserCreationForm(EmailFormMixin, UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = UserModel
        fields = ('username',
                  'email',
                  'password1',
                  'password2'
                  )

        labels = {
            'username': 'Username',
            'email': 'Email',
            'password1': 'Password',
            'password2': 'Repeat Password',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = field.widget.attrs.get('class', '') + ' form-control'
            field.widget.attrs['placeholder'] = f"Enter {self.Meta.labels.get(field_name, field_name).lower()}"


class ProfileBaseForm(EmailFormMixin, forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            'profile_photo',
            'full_name',
            'username_in_marketplace',
            'email',
            'description',
            'country_code',
            'phone',
            'town',
        ]
        labels = {
            'profile_photo': 'Profile Photo',
            'full_name': 'Full Name',
            'username_in_marketplace': 'Name in Marketplace',
            'email': 'Email Address',
            'description': 'Description',
            'country_code': 'Country Code',
            'phone': 'Phone Number',
            'town': 'Town/City',
        }
        widgets = {
            'description': forms.Textarea(attrs={'rows': 4}),
            'profile_photo': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

    def clean_phone(self):
        """
        Custom validation for phone number.
        """
        phone = self.cleaned_data.get('phone')
        if phone:
            if not phone.isdigit():
                raise ValidationError("Phone number must contain only digits.")
            if len(phone) < 9:
                raise ValidationError("Phone number must be at least 9 digits long.")
        return phone

    def clean_full_name(self):
        full_name = self.cleaned_data.get('full_name')
        if full_name and len(full_name.split()) < 2:
            raise forms.ValidationError("Full Name must include at least first name and last name.")
        return full_name

    def clean_profile_photo(self):
        profile_photo = self.cleaned_data.get('profile_photo')
        if profile_photo and profile_photo.size > 5 * 1024 * 1024:
            raise forms.ValidationError("Profile photo size must not exceed 5 MB.")
        return profile_photo

    def __init__(self, *args, **kwargs):
        super(ProfileBaseForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = field.widget.attrs.get('class', '') + ' form-control'
            field.widget.attrs['placeholder'] = f"Enter {self.Meta.labels.get(field_name, field_name).lower()}"


class ProfileCreateForm(ProfileBaseForm):
    pass


class ProfileEditForm(ProfileBaseForm):
    new_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        required=False,
        label="New Password",
    )
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        required=False,
        label="Repeat New Password",
    )

    class Meta:
        model = Profile
        fields = ['profile_photo',
                  'full_name',
                  'username_in_marketplace',
                  'email',
                  'country_code',
                  'phone',
                  'town',
                  'description',
                  ]

        labels = {
            'profile_photo': 'Profile Photo',
            'full_name': 'Full Name',
            'username_in_marketplace': 'Name in Marketplace',
            'email': 'Email Address',
            'description': 'Description',
            'country_code': 'Country Code',
            'phone': 'Phone Number',
            'town': 'Town/City',
            'confirm_password': 'Confirm Password',
            'new_password': 'New Password',
        }

        widgets = {
            'profile_photo': forms.ClearableFileInput(attrs={'class': 'profile-photo-input'}),
            'full_name': forms.TextInput(attrs={'class': 'form-control'}),
            'username_in_marketplace': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'country_code': forms.Select(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'town': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'rows': 4}),
        }

    def clean_new_password(self):
        """
        Custom validation for new password.
        """
        new_password = self.cleaned_data.get("new_password")
        if new_password:
            if len(new_password) < 8:
                raise ValidationError("Password must be at least 8 characters long.")
        return new_password

    def clean(self):
        """
        Perform cross-field validation for the form.
        """
        cleaned_data = super().clean()
        new_password = cleaned_data.get("new_password")
        confirm_password = cleaned_data.get("confirm_password")

        if new_password or confirm_password:
            if new_password != confirm_password:
                self.add_error('confirm_password', "Passwords do not match.")

        return cleaned_data

agro_marketplace/agro_marketplace/accounts/views.py
from datetime import timedelta

from django.contrib import messages
from django.contrib.auth import get_user_model, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.core.paginator import Paginator
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, FormView, UpdateView, View

from .forms import AppUserCreationForm, ProfileCreateForm, CustomAuthenticationForm, ProfileEditForm
from .helper import get_combined_items, get_item_by_slug
from .models import Profile
from django.utils.timezone import now

UserModel = get_user_model()


class AppUserLoginView(LoginView):
    template_name = 'accounts/user-login.html'

    def get_form_class(self):
        return CustomAuthenticationForm


class AppUserRegisterView(CreateView):
    model = UserModel
    form_class = AppUserCreationForm
    template_name = 'accounts/user-registration.html'
    success_url = reverse_lazy('profile-registration')

    def form_valid(self, form):
        response = super().form_valid(form)
        login(self.request, self.object)
        return response


class ProfileRegistrationView(FormView, UpdateView):
    form_class = ProfileCreateForm
    template_name = 'accounts/profile-registration.html'
    success_url = reverse_lazy('dash')

    def get_object(self, queryset=None):
        return Profile.objects.get(user=self.request.user)

    def form_valid(self, form):
        profile = form.save(commit=False)
        profile.user = self.request.user
        profile.save()
        return super().form_valid(form)


def custom_logout(request):
    logout(request)
    messages.info(request, "You have been logged out.")
    return redirect('home')


def profile_details(request, pk):
    profile = get_object_or_404(Profile, pk=pk)
    active_seller_items = profile.seller_products.filter(expiration_date__gte=now())
    active_buyer_items = profile.buyer_products.filter(expiration_date__gte=now())
    context = {
        'profile': profile,
        'active_seller_items': active_seller_items,
        'active_buyer_items': active_buyer_items,
    }
    return render(request, 'accounts/profile-details.html', context)


class EditProfileView(LoginRequiredMixin, UpdateView):
    model = Profile
    form_class = ProfileEditForm
    template_name = 'accounts/profile-edit.html'
    success_url = reverse_lazy('dash')

    def get_object(self, queryset=None):
        return Profile.objects.get(user=self.request.user)

    def form_valid(self, form):
        """
        Handle profile editing and optional password change.
        """
        new_password = self.request.POST.get('new_password')
        confirm_password = self.request.POST.get('confirm_password')

        # Save the updated Profile object
        profile = form.save(commit=False)
        profile.save()

        if new_password or confirm_password:
            if new_password != confirm_password:
                form.add_error(None, "Passwords do not match.")
                return self.form_invalid(form)
            elif new_password.strip() == "":
                form.add_error(None, "Password cannot be blank.")
                return self.form_invalid(form)
            else:
                self.request.user.set_password(new_password)
                self.request.user.save()

                logout(self.request)

                messages.success(self.request, "Password updated successfully. Please log in again.")
                return redirect('login')

        messages.success(self.request, "Profile updated successfully.")
        return super().form_valid(form)


class ProfileDeleteView(LoginRequiredMixin, View):
    template_name = 'accounts/profile-delete.html'

    def get(self, request, pk):
        """Render the profile deletion confirmation page."""
        profile = get_object_or_404(Profile, pk=pk)

        if profile.user != request.user:
            messages.error(request, "You are not authorized to delete this profile.")
            return HttpResponseForbidden("You are not authorized to delete this profile.")

        return render(request, self.template_name, {'profile': profile})

    def post(self, request, pk):
        """Handle profile and user deletion."""
        profile = get_object_or_404(Profile, pk=pk)

        if profile.user != request.user:
            messages.error(request, "You are not authorized to delete this profile.")
            return HttpResponseForbidden("You are not authorized to delete this profile.")

        user = profile.user
        profile.delete()
        user.delete()

        messages.success(request, "Your account and profile have been successfully deleted.")
        return redirect(reverse_lazy('home'))


def delete_item(request, slug):
    item = get_item_by_slug(slug)
    if not item:
        raise Http404("Item not found.")

    is_active = item.expiration_date >= now()

    if request.method == 'POST':
        item.delete()
        return redirect('active-listings' if is_active else 'inactive-listings', pk=item.profile.pk)

    return render(request, 'accounts/item-delete.html', {'object': item})


def activ_listings(request, pk):
    profile = get_object_or_404(Profile, pk=pk)
    combined_items = get_combined_items(profile, expiration_check='active')

    paginator = Paginator(combined_items, 5)
    page_number = request.GET.get('page', 1)
    items_page = paginator.get_page(page_number)

    return render(request, 'accounts/profile-activ-listings.html', {
        'items_page': items_page,
        'profile_pk': pk,
    })


def inactive_listings(request, pk):
    profile = get_object_or_404(Profile, pk=pk)
    combined_items = get_combined_items(profile, expiration_check='inactive')

    paginator = Paginator(combined_items, 5)
    page_number = request.GET.get('page', 1)
    items_page = paginator.get_page(page_number)

    return render(request, 'accounts/profile-inactive-listings.html', {
        'items_page': items_page,
        'profile_pk': pk,
    })


def activate_item(request, slug):
    item = get_item_by_slug(slug, expiration_check='inactive')
    if not item:
        raise Http404("Item not found, expired, or does not belong to the user.")

    item.expiration_date = now() + timedelta(days=30)
    item.save()
    return redirect('inactive-listings', pk=request.user.pk)

agro_marketplace/templates/accounts/item-delete.html
{% extends 'common/base.html' %}
{% load static %}

{% block content %}
    <main class="container">
        <div class="modal-dialog mt-4">
            <div class="modal-content shadow-lg rounded">
                <form method="post">
                    {% csrf_token %}
                    <div class="modal-header bg-danger text-white">
                        <h5 class="modal-title" id="deleteModalLabel">Confirm Deletion</h5>
                    </div>
                    <div class="modal-body text-center">
                        <p class="fs-5">Are you sure you want to delete the item "{{ object.title }}"? This action cannot
                            be
                            undone.</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary mr-5" id="cancelButton">Cancel</button>
                        <button type="submit" class="btn btn-danger px-4 py-2 mx-2">Delete</button>
                    </div>
                    
                </form>
            </div>
        </div>
        </div>
    </main>
{% endblock %}

agro_marketplace/templates/accounts/profile-delete.html
{% extends 'common/base.html' %}
{% load static %}

{% block content %}
    <!-- Main Content -->
    <main class="container my-4">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2 class="text-center mb-4 text-danger">Delete Your Profile</h2>

                <form method="POST" class="p-4 border rounded">
                    {% csrf_token %}
                    <div class="alert alert-warning text-center">
                        <strong>Warning!</strong> This action is permanent and cannot be undone.
                    </div>

                    <!-- Username or Email Field -->
                    <div class="mb-3">
                        <label for="identifier" class="form-label">Username or Email</label>
                        <input type="text" id="identifier" name="identifier" class="form-control"
                               placeholder="Enter your username or email" required>
                    </div>

                    <!-- Password Confirmation Field -->
                    <div class="mb-3">
                        <label for="password" class="form-label">Confirm Password</label>
                        <input type="password" id="password" name="password" class="form-control"
                               placeholder="Enter your password to confirm" required>
                    </div>

                    <!-- Confirm Delete Checkbox -->
                    <div class="mb-3 form-check">
                        <input type="checkbox" class="form-check-input" id="confirmDelete" required>
                        <label class="form-check-label" for="confirmDelete">I understand this action cannot be
                            undone.</label>
                    </div>

                    <!-- Submit Button -->
                    <div class="text-center">
                        <button type="submit" class="btn btn-danger mt-3">Delete Profile</button>
                    </div>
                    <button onclick="goBack()" class="btn btn-secondary">
                        <i class="fas fa-arrow-left"></i> Back
                    </button>
                </form>
            </div>
        </div>
    </main>
{% endblock %}

agro_marketplace/templates/accounts/profile-edit.html
{% extends 'common/base.html' %}
{% load static %}

{% block content %}
    <main class="container my-4">
        <section class="edit-profile">
            <h2>Edit Profile</h2>
            <form action="{% url 'profile-edit' request.user.pk %}" method="POST" enctype="multipart/form-data"
                  class="row g-3">
                {% csrf_token %}

                <!-- Profile Photo -->
                <div class="col-md-12 mb-3 text-center">
                    {% if form.profile_photo.errors %}
                        <div class="alert alert-danger">
                            {{ form.profile_photo.errors }}
                        </div>
                    {% endif %}
                    <div class="profile-photo-container">
                        <img src="
                                
                                {% if form.profile_photo.value %}{{ form.profile_photo.value.url }}{% else %}{% static 'images/profile_picture.webp' %}{% endif %}"
                             alt="Profile Photo" id="profile-img-preview" class="profile-preview-img">
                        <div class="upload-overlay">
                            <i class="fas fa-camera"></i>
                            <input type="file" id="id_profile_photo" name="profile_photo" class="profile-photo-input">
                        </div>
                    </div>
                </div>

                <!-- Full Name -->
                <div class="col-md-6 mb-3">
                    {{ form.full_name.label_tag }}
                    {{ form.full_name }}
                    {% if form.full_name.errors %}
                        <div class="alert alert-danger">
                            {{ form.full_name.errors }}
                        </div>
                    {% endif %}
                </div>

                <!-- Username in Agro Marketplace -->
                <div class="col-md-6 mb-3">
                    {{ form.username_in_marketplace.label_tag }}
                    {{ form.username_in_marketplace }}
                    {% if form.username_in_marketplace.errors %}
                        <div class="alert alert-danger">
                            {{ form.username_in_marketplace.errors }}
                        </div>
                    {% endif %}
                </div>

                <!-- Email -->
                <div class="col-md-6 mb-3">
                    {{ form.email.label_tag }}
                    {{ form.email }}
                    {% if form.email.errors %}
                        <div class="alert alert-danger">
                            {{ form.email.errors }}
                        </div>
                    {% endif %}
                </div>

                <!-- Country Code and Phone -->


                <div class="col-md-2">
                    {{ form.country_code.label_tag }}
                    {{ form.country_code }}
                    {% if form.country_code.errors %}
                        <div class="alert alert-danger">
                            {{ form.country_code.errors }}
                        </div>
                    {% endif %}
                </div>

                <div class="col-md-4">
                    {{ form.phone.label_tag }}
                    {{ form.phone }}
                    {% if form.phone.errors %}
                        <div class="alert alert-danger">
                            {{ form.phone.errors }}
                        </div>
                    {% endif %}
                </div>
                       
                

                <!-- Town -->
                <div class="col-md-6 mb-3">
                    {{ form.town.label_tag }}
                    {{ form.town }}
                    {% if form.town.errors %}
                        <div class="alert alert-danger">
                            {{ form.town.errors }}
                        </div>
                    {% endif %}
                </div>
                 <div class="col-md-6 mb-3">
                    {{ form.description.label_tag }}
                    {{ form.description }}
                     {% if form.description.errors %}
                        <div class="alert alert-danger">
                            {{ form.description.errors }}
                        </div>
                    {% endif %}
                </div>
                <div class="col-12">
                    <h3>Change Password</h3>
                </div>
                <!-- New Password -->
                <div class="row g-3 mb-3">
                    <div class="col-md-6">
                        {{ form.new_password.label_tag }}
                        {{ form.new_password }}
                        {% if form.new_password.errors %}
                            <div class="alert alert-danger">
                                {{ form.new_password.errors }}
                            </div>
                        {% endif %}
                    </div>

                    <div class="col-md-6">
                        {{ form.confirm_password.label_tag }}
                        {{ form.confirm_password }}
                        {% if form.confirm_password.errors %}
                            <div class="alert alert-danger">
                                {{ form.confirm_password.errors }}
                            </div>
                        {% endif %}
                    </div>
                </div>
                <!-- Save Changes Button -->
                <div class="col-12 text-center">
                    <button type="submit" class="btn btn-primary mt-3">Save Changes</button>
                </div>

                <!-- Back Button -->
                <div class="col-12">
                    <a href="{% url 'dash' %}" class="btn btn-secondary">
                        <i class="fas fa-arrow-left"></i> Back
                    </a>
                </div>
            </form>
        </section>
    </main>
{% endblock %}

agro_marketplace/templates/accounts/profile-registration.html
{% extends 'common/base.html' %}
{% load static %}

{% block content %}
    <main class="container my-5">
        <h2>Join - Agro Marketplace</h2>
        <form method="POST" action="{% url 'profile-registration' %}" enctype="multipart/form-data"
              class="row g-4 justify-content-center">
            {% csrf_token %}
            <!-- Profile Photo Upload -->
            <div class="col-md-6">
                {% if form.profile_photo.errors %}
                    <div class="alert alert-danger">
                        {{ form.profile_photo.errors }}
                    </div>
                {% endif %}
                <div class="col-md-4">
                    <div class="profile-photo-container">
                        <img
                                id="profile-img-preview"
                                src="
                                        {% if form.profile_photo.value %}{{ form.profile_photo.value.url }}{% else %}{% static 'images/profile_picture.webp' %}{% endif %}"
                                alt="Profile Preview"
                                class="img-thumbnail rounded-circle profile-photo-preview">
                    </div>
                </div>

                <div class="col-md-8 btn-profile">
                    <!-- Upload Button -->
                    <div class="mt-2">
                        <button
                                type="button"
                                class="btn btn-primary"
                                onclick="document.getElementById('id_profile_photo').click();">
                            Upload Photo
                        </button>
                    </div>
                    <div class="d-none">
                        {{ form.profile_photo }}
                    </div>
                </div>
            </div>

            <div class="col-md-6 mt-5">
                {{ form.full_name.label_tag }}
                {{ form.full_name }}
                {% if form.full_name.errors %}
                    <div class="alert alert-danger">
                        {{ form.full_name.errors }}
                    </div>
                {% endif %}
            </div>
            <div class="col-md-6">
                {{ form.username_in_marketplace.label_tag }}
                {{ form.username_in_marketplace }}
                {% if form.username_in_marketplace.errors %}
                    <div class="alert alert-danger">
                        {{ form.username_in_marketplace.errors }}
                    </div>
                {% endif %}
            </div>
            <div class="col-md-6">
                {{ form.email.label_tag }}
                {{ form.email }}
                {% if form.email.errors %}
                    <div class="alert alert-danger">
                        {{ form.email.errors }}
                    </div>
                {% endif %}
            </div>
            <!-- Description -->
            <div class="col-md-12">
                {{ form.description.label_tag }}
                {{ form.description }}
                {% if form.description.errors %}
                    <div class="alert alert-danger">
                        {{ form.description.errors }}
                    </div>
                {% endif %}
            </div>
            <div class="col-md-2">
                {{ form.country_code.label_tag }}
                {{ form.country_code }}
                {% if form.country_code.errors %}
                    <div class="alert alert-danger">
                        {{ form.country_code.errors }}
                    </div>
                {% endif %}
            </div>
            <div class="col-md-4">
                {{ form.phone.label_tag }}
                {{ form.phone }}
                {% if form.phone.errors %}
                    <div class="alert alert-danger">
                        {{ form.phone.errors }}
                    </div>
                {% endif %}
            </div>
            <div class="col-md-6">
                {{ form.town.label_tag }}
                {{ form.town }}
                {% if form.town.errors %}
                    <div class="alert alert-danger">
                        {{ form.town.errors }}
                    </div>
                {% endif %}
            </div>
            <div class="col-12 text-center mt-3">
                <button type="submit" class="btn btn-primary">Register</button>
            </div>
        </form>
    </main>
{% endblock %}